//
//  Constants.h
//  TestGUI
//
//  Created by Albert Palacios Jimenez on 22/12/23.
//

#ifndef Constants_h
#define Constants_h

#ifdef GNS

#define CTBezelStyleAccessoryBarAction NSRoundRectBezelStyle
#define CTBezelStylePush NSRoundedBezelStyle
#define CTBezelStyleSmallSquare NSSmallSquareBezelStyle
#define CTBezelStyleFlexiblePush NSRegularSquareBezelStyle // Same as : NSThickerSquareBezelStyle, NSThickSquareBezelStyle
#define CTBezelStyleShadowlessSquare NSShadowlessSquareBezelStyle
#define CTBezelStyleCircular NSCircularBezelStyle
#define CTBezelStyleDisclosure NSDisclosureBezelStyle
#define CTBezelStylePushDisclosure NSRoundedDisclosureBezelStyle
#define CTBezelStyleHelpButton NSHelpButtonBezelStyle
#define CTBezelStyleAccessoryBar NSRecessedBezelStyle
#define CTBezelStyleTexturedSquare NSTexturedSquareBezelStyle
#define CTBezelStyleTexturedRounded NSTexturedRoundedBezelStyle
#define CTBezelStyleToolbar NSTexturedRoundedBezelStyle

#define CTButtonTypePushOnPushOff NSPushOnPushOffButton
#define CTButtonTypeMomentaryPushIn NSMomentaryPushInButton

#else

#define CTBezelStyleAccessoryBarAction NSBezelStyleAccessoryBarAction
#define CTBezelStylePush NSBezelStylePush
#define CTBezelStyleSmallSquare NSBezelStyleSmallSquare
#define CTBezelStyleFlexiblePush NSBezelStyleFlexiblePush
#define CTBezelStyleShadowlessSquare NSBezelStyleShadowlessSquare
#define CTBezelStyleCircular NSBezelStyleCircular
#define CTBezelStyleDisclosure NSBezelStyleDisclosure
#define CTBezelStylePushDisclosure NSBezelStylePushDisclosure
#define CTBezelStyleHelpButton NSBezelStyleHelpButton
#define CTBezelStyleAccessoryBar NSBezelStyleAccessoryBar
#define CTBezelStyleTexturedSquare NSBezelStyleTexturedSquare
#define CTBezelStyleTexturedRounded NSBezelStyleTexturedRounded
#define CTBezelStyleToolbar NSBezelStyleToolbar

#define CTButtonTypePushOnPushOff NSButtonTypePushOnPushOff
#define CTButtonTypeMomentaryPushIn NSButtonTypeMomentaryPushIn

#endif

#endif /* Constants_h */
